// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwVph3NlN5msetccic9XiKj7mpHEhA-AY',
    appId: '1:745240441872:web:0ba2f28ce63b6a46bac695',
    messagingSenderId: '745240441872',
    projectId: 'flutterquotes-30991',
    authDomain: 'flutterquotes-30991.firebaseapp.com',
    storageBucket: 'flutterquotes-30991.appspot.com',
    measurementId: 'G-JQK5C3E468',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_84pgYfdcS6cXMMHgJfGoXOXIGKKYFO0',
    appId: '1:745240441872:android:b92af294895e277cbac695',
    messagingSenderId: '745240441872',
    projectId: 'flutterquotes-30991',
    storageBucket: 'flutterquotes-30991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6xq5Y1hp1NsS5k38z_F_4oC_4AZU7TEU',
    appId: '1:745240441872:ios:69d294bff5b6ae12bac695',
    messagingSenderId: '745240441872',
    projectId: 'flutterquotes-30991',
    storageBucket: 'flutterquotes-30991.appspot.com',
    iosClientId: '745240441872-4i40n14g9i968j9mk2qliqkpvjejbvaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.quotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6xq5Y1hp1NsS5k38z_F_4oC_4AZU7TEU',
    appId: '1:745240441872:ios:69d294bff5b6ae12bac695',
    messagingSenderId: '745240441872',
    projectId: 'flutterquotes-30991',
    storageBucket: 'flutterquotes-30991.appspot.com',
    iosClientId: '745240441872-4i40n14g9i968j9mk2qliqkpvjejbvaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.quotesApp',
  );
}
